// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afnctctxrprpnysndgtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmbmN0Y3R4cnBycG55c25kZ3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTY1NjcsImV4cCI6MjA2NzEzMjU2N30.hx6cJXyd1qDsYDRJhRm0z-vkhtdlP-aOgrIqXqgqW38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});